### ISSUE TITLE
switch to ESM

### ISSUE THREAD

**Issue by philippkuehn** [holtwick/hostic-dom#2]
Since [ESM is here](https://blog.sindresorhus.com/hello-modules-d1010b4e777b), it would be nice to update your package.json. What do you think?

**Comment by holtwick** [comment]
Yes and Typescript. Hope I can allocate some time for it next week.

**Comment by holtwick** [comment]
I made some changes, but won't break things for TipTap ;) Could you take a look if the ESM part looks ok for you, @philippkuehn ? Thanks. 

PR https://github.com/holtwick/hostic-dom/pull/3

**Comment by holtwick** [comment]
@philippkuehn would you like to take a look at PR #3 if it is what you expected? Thanks.

**Comment by holtwick** [comment]
Hi @philippkuehn 

I rebranded hostic-dom to https://github.com/holtwick/zeed-dom It is ESM and fully written in Typescript now. Should make life easier ;) Please consider switching to this one, I'm considering to retire the hostic things.

cc @hanspagel

**Comment by hanspagel** [comment]
Amazing! We’ll switch soonish.
