### ISSUE TITLE
`camel` as a not working as an object key

### ISSUE THREAD

**Issue by SamDuvall** [holtwick/hostic-dom#4]
I'm running into an issue in TipTap where my build won't create the `camel` version, because `camel` is a function. Obviously, this works in the TipTap demo, so there must be something different about my setup. Is there a Babel/Typescript configuration that allows object keys to be functions? Did you intend for `camel` to be a function instead of a string?

https://github.com/holtwick/hostic-dom/blob/b4a214f6f4c80974810eb5f60ae0ca400ea465a9/src/vdom.js#L401-L403

**Comment by holtwick** [comment]
You cannot pass other values than strings as keys to objects. `camel` is a function in your example. Did you mean this?

```js
styles[camel(key)] = value
```

Please provide a link to the TipTap sample you are referring to.

**Comment by SamDuvall** [comment]
Okay. I was fairly certain that only strings could be object keys, but I just wanted to make sure I hadn't missed some spec I wasn't aware of.

TipTap is passing through the styles as part of an `HTMLElement`, so my expectation (from the TipTap api) would be that element.style contain camelCase keys exclusively (see [here](CSSStyleDeclaration)).

The TipTap demo I was referring to is [here](https://www.tiptap.dev/api/extensions/font-family/#fontfamily). On second glance, I think that demo uses a browser-based HTML parser, instead of `hostic-dom`. However, I'm running into issues using TipTap's server-side HTML parser where `hostic-dom` is used: https://github.com/ueberdosis/tiptap/blob/main/packages/html/src/generateJSON.ts#L4.

On a slightly related note, do you have any plans on adding `element.dataset` into `hostic-dom`? I'd prefer to use `dataset` over `getAttribute(data-xxxx)`, if possible.

**Comment by holtwick** [comment]
I made a new DOM library based on hostic-dom here  https://github.com/holtwick/zeed-dom

It is written in Typescript and support ESM properly.

I suggested to TipTap to switch to this https://github.com/holtwick/hostic-dom/issues/2

I incorporated @sibiraj-s fix in it as well. See https://github.com/holtwick/zeed-dom/commit/84cc0d961fa3ecedfe6b1a465c6d821794c59bc3

**Comment by holtwick** [comment]
I also applied the fix to hostic-dom

**Comment by sibiraj-s** [comment]
Thanks @holtwick.

BTW. https://github.com/holtwick/zeed-dom page is not accessible

**Comment by holtwick** [comment]
🤦‍♂️ I made it public now ;) Thank you for your help!

**Comment by sibiraj-s** [comment]
Thanks @holtwick 🚀 .

One last question. Is there any changes to API/behaviour in zeed-dom. Or it just a typescript version?

**Comment by holtwick** [comment]
Just Typescript and ESM and some small fixes. It directly evolved from hostic-dom.

**Comment by sibiraj-s** [comment]
Thanks @holtwick
